### ISSUE TITLE
http_proxy https_proxy dont work

### ISSUE THREAD

**Issue by patsevanton** [solval/ansible-role-gitlab_runner#2]
Hi!
I try install gitlab runner using proxy squid.
But http_proxy https_proxy dont work.

```
cat gitlab-runner.yml 
- hosts: gitlab-runner
  become: yes
  roles:
    - solval.gitlab_runner
  vars:
    proxy_env:
      http_proxy: http://192.168.88.249:3128
      https_proxy: http://192.168.88.249:3128
```

> <192.168.88.220> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/a6cd09958a -tt 192.168.88.220 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ushiwkpddwognxqcdxkdxwutujijawag; no_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' https_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' http_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' ansible_user_id=root socks_proxy='"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1542262804.26-128605014287447/rpm_key.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
> Escalation succeeded
> <192.168.88.220> (1, '\r\n{"msg": "Failed to connect to packages.gitlab.com at port 443: [Errno 101] \\u0421\\u0435\\u0442\\u044c \\u043d\\u0435\\u0434\\u043e\\u0441\\u0442\\u0443\\u043f\\u043d\\u0430", "failed": true, "exception": "  File \\"/tmp/ansible_YglE0x/ansible_modlib.zip/ansible/module_utils/urls.py\\", line 1055, in fetch_url\\n    client_key=client_key, cookies=cookies)\\n  File \\"/tmp/ansible_YglE0x/ansible_modlib.zip/ansible/module_utils/urls.py\\", line 958, in open_url\\n    r = urllib_request.urlopen(*urlopen_args)\\n  File \\"/usr/lib64/python2.7/urllib2.py\\", line 154, in urlopen\\n    return opener.open(url, data, timeout)\\n  File \\"/usr/lib64/python2.7/urllib2.py\\", line 429, in open\\n    req = meth(req)\\n  File \\"/tmp/ansible_YglE0x/ansible_modlib.zip/ansible/module_utils/urls.py\\", line 775, in http_request\\n    raise ConnectionError(\'Failed to connect to %s at port %s: %s\' % (self.hostname, self.port, to_native(e)))\\n", "invocation": {"module_args": {"state": "present", "validate_certs": true, "key": "https://packages.gitlab.com/gpg.key"}}}\r\n', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.1, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug1: /home/user/.ssh/config line 1: Applying options for *\r\ndebug1: /home/user/.ssh/config line 7: Applying options for 192.168.88.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16179\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 192.168.88.220 closed.\r\n')
> <192.168.88.220> ESTABLISH SSH CONNECTION FOR USER: user
> <192.168.88.220> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/a6cd09958a 192.168.88.220 '/bin/sh -c '"'"'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1542262804.26-128605014287447/ > /dev/null 2>&1 && sleep 0'"'"''
> <192.168.88.220> (0, '', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.1, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug1: /home/user/.ssh/config line 1: Applying options for *\r\ndebug1: /home/user/.ssh/config line 7: Applying options for 192.168.88.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16179\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
> The full traceback is:
>   File "/tmp/ansible_YglE0x/ansible_modlib.zip/ansible/module_utils/urls.py", line 1055, in fetch_url
>     client_key=client_key, cookies=cookies)
>   File "/tmp/ansible_YglE0x/ansible_modlib.zip/ansible/module_utils/urls.py", line 958, in open_url
>     r = urllib_request.urlopen(*urlopen_args)
>   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib64/python2.7/urllib2.py", line 429, in open
>     req = meth(req)
>   File "/tmp/ansible_YglE0x/ansible_modlib.zip/ansible/module_utils/urls.py", line 775, in http_request
>     raise ConnectionError('Failed to connect to %s at port %s: %s' % (self.hostname, self.port, to_native(e)))
> 
> fatal: [gitlab-runner]: FAILED! => {
>     "changed": false, 
>     "invocation": {
>         "module_args": {
>             "key": "https://packages.gitlab.com/gpg.key", 
>             "state": "present", 
>             "validate_certs": true
>         }
>     }
> }
> 
> MSG:
> 
> Failed to connect to packages.gitlab.com at port 443: [Errno 101] Сеть недоступна

**Comment by patsevanton** [comment]
environment dont work 
```
cat gitlab-runner.yml 
- hosts: gitlab-runner
  become: yes
  roles:
    - solval.gitlab_runner
  environment:
    http_proxy: http://192.168.88.249:3128
    https_proxy: http://192.168.88.249:3128
```

If rewrite task that work
```
- name: RHEL Install GitLab GPG
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key
  environment:
    http_proxy: http://192.168.88.249:3128
    https_proxy: http://192.168.88.249:3128
  become: yes
```

**Comment by jakub-d** [comment]
This role takes proxy settings from environment variables.
You can remove proxy settings from your .yml files. Then run:
```
export http_proxy=http://192.168.88.249:3128
export https_proxy=http://192.168.88.249:3128
ansible-playbook ...
```

**Comment by patsevanton** [comment]
Thanks!
